# Datos

lista_competencias = {
    'ADAPTABILIDAD  Y TRABAJO EN EQUIPO': {
        'descripcion': 'Hace referencia a la Capacidad para establecer vínculos con los compañeros, apoyándolos, generando confianza y respeto. Asociado con ser referente de sus pares de forma tal que todos quieran compartir conocimientos y apoyo de manera informal. Habilidad para genera reconocimiento mediante el servicio y la empatía con la gente. Implica la intención de colaborar, cooperar y trabajar con los demás, como una actitud opuesta a lo individual y competitivo. Capacidad de expresar satisfacción por los compañeros del equipo o de otras líneas. Habilidad para preocuparse por apoyar el desempeño de otros. Disposición para sacrificar intereses personales cuando sea necesario en beneficio de los objetivos organizacionales.',
        'apto': 'Capacidad para promover entre sus pares la actitud de compartir informalmente los conocimientos, apoyándolos y recibiendo apoyo. Puede valorar y reconocer a los demás. Tiene reconocimiento entre sus pares por generar confianza y respeto.  Crea un ambiente de trabajo amistoso. Valora las ideas y experiencias de los demás y mantiene una actitud abierta para aprender de otros. Implica seguir adelante en medio de circunstancias adversas.',
        'apto_min': 0,
        'apto_max': 11,
        'apto_condicionado': 'Prioriza los trabajos que le son asignados en forma individual quedando en segundo plano las tareas que demandan intercambio de información o reuniones con el equipo. Puede obstaculizar con actitud desvalorizadora el momento de intercambio de ideas, con la prioridad de terminar lo propio. En ocasiones se muestra molesto cuando recibe sugerencias o propuestas de sus pares o jefe.',
        'apto_condicionado_min': 12,
        'apto_condicionado_max': 13,
        'no_apto': 'Incapacidad para participar activamente y compartir logros con los compañeros de trabajo.',
        'no_apto_min': 14,
        'no_apto_max': 24,
        'tipo': 0,
        'contra_titulo': 'INADAPTABILIDAD',
    },
    'CULTURA DE AUTOCUIDADO': {
        'descripcion': 'Es la capacidad de preservar las normas de seguridad e higiene por convicción y promoverla entre los compañeros. Se refiere a una conducta que se dirige hacia sí mismo o hacia el entorno para regular los factores que afectan a su propio desarrollo y actividad en beneficio de la vida, salud y bienestar.',
        'apto': 'Posee las capacidades para cumplir con las normas de seguridad e higiene para preservar su calidad de vida.',
        'apto_min': 0,
        'apto_max': 19,
        'apto_condicionado': 'Requiere que se le especifiquen las normas de seguridad e higiene y un mínimo de supervisión para que sea acatadas.',
        'apto_condicionado_min': 20,
        'apto_condicionado_max': 20,
        'no_apto': 'Tiene dificultad para preservar su calidad de vida, puede infringir los reglamentos de seguridad aun conociéndolos o acatarlos solo cuando se sabe observado. Es importante relacionar este con el rublo de impulsividad, si en ambos la ponderación es no apto el riesgo se maximiza.',
        'no_apto_min': 21,
        'no_apto_max': 42,
        'tipo': 0,
        'contra_titulo': 'NEGLIGENCIA',
    },
    'IMPULSIVIDAD': {
        'descripcion': 'Implica respuestas caracterizadas por responder rápido y sin demasiado análisis, generado cuando la persona se enfrenta a problemáticas que cuentan con varias opciones de solución. Es la capacidad para controlar emociones personales y evitar reacciones negativas. Es la tendencia a proceder de momento sin tener en cuentas las consecuencias a futuro, actuar sin pensar. Falta de una evaluación adecuada del contexto, dificultad para retardar las recompensas y la toma de decisiones rápidas.',
        'apto': 'La mayor parte del tiempo se puede mantener sereno y firme en situaciones complejas o adversas, focalizándose en el logro de sus objetivos. Trabaja con constancia y perseverancia aun en situaciones difíciles. Está atento a cambios en el ritmo de trabajo que pueden generar alta exigencia y posibles roses, actúa con tolerancia y promueve la misma actitud en sus compañeros de trabajo.',
        'apto_min': 0,
        'apto_max': 18,
        'apto_condicionado': 'La mayor parte del tiempo mantiene la calma aun cuando se siente impulsado a reaccionar inmediatamente, evaluando las posibles consecuencias de sus actos. Mantiene estable su rendimiento, aunque el clima laboral siempre y cuando el clima laboral sea favorable. Puede buscar apoyo cuando se ve superado por las situaciones que se presentan a fin de resolverlas con efectividad.',
        'apto_condicionado_min': 19,
        'apto_condicionado_max': 20,
        'no_apto': 'Suele conducirse de forma impulsiva, generando reacciones negativas entre compañeros. Actúa notablemente molesto en momentos de trabajo de alta exigencia, viéndose mermado su rendimiento. Puede generar conflictos constantemente, obstaculizando acciones rápidas en jornadas de trabajo de alta exigencia. En épocas de alta presión, quizá actúe desequilibradamente en sus reacciones haca sus pares, aportando más tensión, generando un clima laboral conflictivo y bajando el rendimiento de su área.',
        'no_apto_min': 21,
        'no_apto_max': 55,
        'tipo': 1,
        'contra_titulo': 'CONTROL DE IMPULSOS',
    },
    'MANEJO DE CONFLICTOS':{
        'descripcion': 'Es la capacidad para justificar o explicar los problemas surgidos, los fracasos o los acontecimientos negativos. Implica seguir adelante en medio de circunstancias adversas. Se asocia a la versatilidad del comportamiento para adaptarse a distintos contextos, situaciones y personas de forma rápida y adecuada. Habilidad para establecer relaciones efectivas con individuos y grupos complejos.',
        'apto': 'Mantiene el control en relaciones problemáticas. Muestra creatividad al momento de presentar soluciones a situaciones difíciles. Puede establecer relaciones convenientes para toda la organización. En contextos favorables puede obtener la cooperación y el apoyo de ciertas personas, para el logro de los objetivos buscados por la organización.',
        'apto_min': 0,
        'apto_max': 23,
        'apto_condicionado': 'En contextos no favorables puede presentar sensación de minusvalía y alta susceptibilidad.',
        'apto_condicionado_min': 24,
        'apto_condicionado_max': 26,
        'no_apto': 'Le cuesta trabajo establecer relaciones con personas y grupos complejos. Solo opera de forma adecuada cuando se mueve dentro de vínculos conocidos. Probablemente tenga dificultades para obtener apoyo de los demás para llevar a cabo las tareas organizacionales. Puede presentar sensación de minusvalía e ideas no fundamentadas sobre una percepción negativa de sus compañeros y jefes.',
        'no_apto_min': 27,
        'no_apto_max': 116,
        'tipo': 0,
        'contra_titulo': 'SUCEPTIBILIDAD INTERPERSONAL',
    },
    'APEGO A LA NORMA':{
        'descripcion': 'Es la capacidad de seguir instrucciones, se asocia con el cumplimiento a los reglamentos establecidos por la compañía. La normatividad asignada está primero.',
        'apto': 'El trabajador tiene aceptación hacía normativa de la institución, teniendo el conocimiento adecuado de las reglas le será fácil entender lo que se espera de él en cuanto a sus conductas. Puede seguir las instrucciones que le dé la autoridad. Capacidad para desempeñar las tareas con dedicación, cuidando cumplir tanto con los plazos como con la calidad requerida y aspirando a alcanzar el mejor resultado posible.',
        'apto_min': 0,
        'apto_max': 15,
        'apto_condicionado': 'Requiere conocer y que le expliquen las normas institucionales tanto las escritas como las implícitas, tendrá dificultad con las reglas que sean ambiguas y las puede interpretar de acuerdo a su interés personal. Capacidad para cumplir con los plazos tomando todos los márgenes de tolerancia previstos y la calidad mínima necesaria para lograr el objetivo.',
        'apto_condicionado_min': 16,
        'apto_condicionado_max': 17,
        'no_apto': 'Presenta conflictos con la autoridad, también se asocia con conductas deshonestas. Aun conociendo las normas institucionales podrá no acatarlas. Requiere supervisión permanente. Cumple con plazos o alcanza la calidad, pero difícilmente ambas cosas a la vez.',
        'no_apto_min': 18,
        'no_apto_max': 78,
        'tipo': 0,
        'contra_titulo': 'REBELDÍA',
    },
    'RIESGO ADICTIVO': {
        'descripcion': 'Es el uso regular de substancias que alteran el equilibrio del organismo, pueden ser drogas ilícitas, alcohol o auto prescripción de fármacos.',
        'apto': 'No presenta conductas asociadas a riesgo psicosocial, especialmente a riesgo adictivo. Tiende a rechazar el consumo de sustancias restringidas en el trabajo, pues considera que entorpecen el buen desempeño laboral.',
        'apto_min': 0,
        'apto_max': 3,
        'apto_condicionado': 'La escala no mide consumo expreso de substancias, por lo que no se puede aseverar que la persona es consumidora, sin embargo, se encuentra en un ambiente de riesgo que puede ser promotor adictivo y de conductas agresivas.',
        'apto_condicionado_min': 4,
        'apto_condicionado_max': 5,
        'no_apto': 'La escala no mide consumo expreso de substancias, por lo que no se puede aseverar que la persona es consumidora, sin embargo, informa riesgo de pares y conductas violentas. Cuando ambos factores correlacionan regularmente está asociado a una conducta de abuso de substancias. Se recomienda especificar las normas institucionales en cuanto a consumo de drogas o alcohol.',
        'no_apto_min': 6,
        'no_apto_max': 27,
        'tipo': 1,
        'contra_titulo': 'ENTORNOS SALUDABLES',
    },
    'VIOLENCIA': {
        'descripcion': 'Es al acto intencional de dañar a otra persona o ser vivo ya sea de forma física o psicológica. Implica violencia contra sí mismo, otra persona o un grupo sea en grado de amenaza o efectivo.',
        'apto': 'Presenta conductas asertivas y no tiene indicadores de violencia.',
        'apto_min': 0,
        'apto_max': 5,
        'apto_condicionado': 'Bajo ciertos estresores puede tener conductas violentas, se recomienda asociar la información con el indicador de Impulsividad y confrontarlo con adaptabilidad, así como con la entrevista. Si en los indicadores previos se presenta con No apto es condicional de riesgo.',
        'apto_condicionado_min': 6,
        'apto_condicionado_max': 7,
        'no_apto': 'La persona presenta conductas violentas que pueden afectar significativamente las relaciones interpersonales y con esto perturbar el clima laboral y los procesos productivos. Puede no reconocer dicha conducta por tenerla normalizada dentro de su contexto social.',
        'no_apto_min': 8,
        'no_apto_max': 45,
        'tipo': 1,
        'contra_titulo': 'CONVIVENCIA PACÍFICA',
    },
    'LIDERAZGO NEGATIVO': {
        'descripcion': 'Se refiere a un inadecuado uso del poder entre iguales que cuando no es conveniente se vuelve abusivo y agotador. Posee la capacidad de influir negativamente y puede ser utilizado en su beneficio o en contra de la empresa.',
        'apto': 'Su posibilidad de control lo utiliza a favor de la empresa. Tiene la capacidad de influir de manera positiva o negativa en su lugar de trabajo. Se refiere al apego a normas aun cuando no se encuentre de acuerdo.',
        'apto_min': 0,
        'apto_max': 6,
        'apto_condicionado': 'Puede presentar conductas de alianza con los compañeros en contra de la autoridad. Cuestiona los objetivos comunes, desorganizando el curso de las acciones de todo su equipo de trabajo. No percibe el efecto tipo o negativo de sus acciones. Se requiere explicitarle las rutas para expresar su posible inconformidad  por las vías formales.',
        'apto_condicionado_min': 7,
        'apto_condicionado_max': 8,
        'no_apto': 'La persona puede persuadir a los compañeros de trabajo para efectuar conductas en contra de la autoridad, es posible que la causa sea justa, sin embargo, falla en el procedimiento de hacer valer sus derechos. Los demás no saben qué esperar de él. No siente compromiso con la visión y los objetivos de la organización, y transmite apatía al equipo.',
        'no_apto_min': 9,
        'no_apto_max': 32,
        'tipo': 1,
        'contra_titulo': 'LIDERAZGO POSITIVO',
    },
}

lista_conductas = {
    'Likert1': [
        [1,'Disfruto estar con otras personas. ',True,(3,2,1,0)],
        [2,'Mentir es malo solo si me descubren.',False,(0,1,2,3)],
        [3,'Soy cuidadosa/o.',True,(3,2,1,0)],
        [4,'No importa mentir a alguien si con ello evito problemas.',False,(0,1,2,3)],
        [5,'Alguno de mis amigo/as han usado drogas.',False,(0,1,2,3)],
        [6,'Pierdo la paciencia a menudo.',False,(0,1,2,3)],
        [7,'Digo lo primero que se me viene a la cabeza.',False,(0,1,2,3)],
        [8,'Planeo cosas con anticipación.',True,(3,2,1,0)],
        [9,'A mi familia le molestan mis amigas/os.',False,(0,1,2,3)],
        [10,'Pienso mis decisiones a futuro. ',True,(3,2,1,0)],
        [11,'Durante la adolescencia me escapé alguna vez de casa y pasé la noche fuera.',False,(0,1,2,3)],
        [12,'Realizo actividades que le sirven a otros. ',True,(3,2,1,0)],
        [13,'Acostumbro a comer aun cuando no tengo hambre.',False,(0,1,2,3)],
        [14,'Reconozco y valoro las ideas de los demás. ',True,(3,2,1,0)],
        [15,'Soy impulsivo/a.',False,(0,2,3,4)],
        [16,'Me considero una persona optimista. ',True,(3,2,1,0)],
        [17,'He amenazado a otros con hacerles daño o lastimarlos.',False,(0,3,4,5)],
        [18,'Sé decir no cuando algo me molesta.',True,(3,2,1,0)],
        [19,'He dañado intencionalmente las cosas de otros.',False,(0,3,4,5)],
        [20,'Me he peleado físicamente con  amigas/os o familiares.',False,(0,1,2,3)],
        [21,'He molestado o le he hecho daño a los animales.',False,(0,3,4,5)],
        [22,'Se han aburrido mis amigas/os en las fiestas donde no hay tragos.',False,(0,1,2,3)],
        [23,'Las decisiones que afectan a mi vida y a mi trabajo las tomo con rapidez.',False,(0,1,2,3)],
        [24,'Me opongo a las normas porque quitan libertad a la gente.',False,(0,1,2,3)],
        [25,'Me gusta o gustaría manejar rápido.',False,(0,1,2,3)],
        [26,'Me siento en capacidad de expresarme cuando no estoy de acuerdo.',False,(0,1,2,3)],
        [27,'Me gusta cambiar de casa.',False,(0,1,2,3)],
        [28,'Me siento valorado/a por otros. ',True,(3,2,1,0)],
        [29,'Me interesa dedicar tiempo a cosas en las que no gano nada.',True,(3,2,1,0)],
        [30,'Soy buena compañía para otras personas. ',True,(3,2,1,0)],
        [31,'Me resulta difícil controlar las emociones.',False,(0,1,2,3)],
        [32,'Mis amigas/os han tenido problemas con las autoridades.',False,(0,1,2,3)],
        [33,'No me gusta esperar en una fila.',False,(0,1,2,3)],
        [34,'Termino las cosas que empiezo.',True,(3,2,1,0)],
        [35,'Me es fácil concentrarme.',False,(0,1,2,3)],
        [36,'Tengo más de tres personas con quien hablar de las cosas que son muy personales.',True,(3,2,1,0)],
        [37,'Me siento satisfecho conmigo  y con lo que hago.',True,(3,2,1,0)],
        [38,'Soy más valiente que la mayoría de mis compañeros/as.',False,(0,1,2,3)],
        [39,'Perdía los útiles escolares.',False,(0,1,2,3)],
        [40,'Terminaba las tareas muy rápido. ',False,(0,1,2,3)],
        [41,'Trataba de ser el primero en los juegos.',False,(0,1,2,3)],
        [42,'Primero hacia las tareas fáciles y después las difíciles.',False,(0,1,2,3)],
        [43,'Era muy activa/o',False,(0,1,2,3)],
        [44,'Me gustaba desarmar cosas.',False,(0,1,2,3)],
        [45,'Me aburría en el salón de clases.',False,(0,1,2,3)],
        [46,'Me distraía con facilidad.',False,(0,3,4,5)],
        [47,'Tenía dificultad para esperar los turnos.',False,(0,1,2,3)],
        [48,'Me costaba trabajo estar mucho tiempo en mi silla.',False,(0,1,2,3)],
        [49,'Me costaba dormirme.',False,(0,1,2,3)],
        [50,'Dejaba la tarea para el final del día.',False,(0,1,2,3)],
        [51,'Defendía a golpes a mis compañeros/as.',False,(0,1,2,3)],
        [52,'Era inquieta/o, me movía de un lugar a otro.',False,(0,1,2,3)],
        [53,'Pelaba con las/los compañeras/os.',False,(0,3,4,5)],
        [54,'Me costaba trabajo levantarme.',False,(0,1,2,3)],
        [55,'Me molestaba que me dieran órdenes.',False,(0,1,2,3)],
        [56,'Me metía en problemas constantemente con mis compañeros.',False,(0,1,2,3)],
        [57,'Empezaba las actividades antes de los otros niños/as.',False,(0,1,2,3)],
        [58,'Cambiaba fácilmente de una actividad a otra.',False,(0,1,2,3)],
        [59,'Culpaba a otras/os niñas/os de las travesuras que yo hacía.',False,(0,1,2,3)],
        [60,'Me costaba trabajo esperar.',False,(0,1,2,3)],
        [61,'Me gustaba hacer muchas cosas al mismo tiempo.',False,(0,1,2,3)]
    ],
    'Likert2': [
        [62,'Alguna vez fueron tan agresivas/os conmigo que grite o golpee.',False,(0,3,4,5,6)],
        [63,'Era difícil confiar en mis compañeras/os o jefes.',False,(0,1,2,3,4)],
        [64,'Eran poco comprensivos conmigo.',False,(0,1,2,3,4)],
        [65,'Me criticaban en mi forma de ser o trabajar.',False,(0,1,2,3,4)],
        [66,'Me hacían explotar por comentarios o acciones de mis compañeras/os o jefes.',False,(0,3,4,5,6)],
        [67,'Me hacían sentir menos o que no valía.',False,(0,1,2,3,4)],
        [68,'Me involucraba frecuentemente en discusiones.',False,(0,3,4,5,6)],
        [69,'Las/los compañeras/os hacían cosas mal y a mi me culpaban.',False,(0,1,2,3,4)],
        [70,'Las/los compañeras/os o jefes eran poco amistosos/as.',False,(0,1,2,3,4)],
        [71,'Me comportaba con timidez.',False,(0,1,2,3,4)],
        [72,'Me sentía  incómoda/o al comer con mis compañeras/os.',False,(0,1,2,3,4)],
        [73,'Me sentía incómoda/o cuando la gente me miraba o hablaba de mí.',False,(0,1,2,3,4)],
        [74,'Me sentía enojada/o.',False,(0,1,2,3,4)],
        [75,'Me sentía herida/o o lastimada/o por mis compañeros o jefes.',False,(0,1,2,3,4)],
        [76,'Me sentía muy tímida/o con los demás.',False,(0,1,2,3,4)],
        [77,'Si tenían oportunidad mis compañeras/os se aprovechaban de mí.',False,(0,1,2,3,4)],
        [78,'Mis compañeras/os hablaban a mis espaldas.',False,(0,2,3,4,5)],
        [79,'Mis compañeras/os o jefes no valoraban mis logros.',False,(0,1,2,3,4)],
        [80,'Mis compañeras/os o jefes se oponían a mi forma de pensar.',False,(0,1,2,3,4)]
    ]
}

lista_competencias_conductas = {
    'ADAPTABILIDAD  Y TRABAJO EN EQUIPO': [1,12,14,16,18,26,28,30],
    'CULTURA DE AUTOCUIDADO': [3,8,10,12,14,16,18,26,28,30,34,35,36,37], 
    'IMPULSIVIDAD': [7,41,47,23,42,48,54,13,15,27,33,40,43,45,49,52,58,60],
    'MANEJO DE CONFLICTOS': [17,19,21,45,48,49,53,55,56,59,60,62,63,64,65,66,67,68,69,70,72,73,74,75,77,78,79,80],
    'APEGO A LA NORMA': [15,19,20,24,25,27,31,39,45,46,47,48,49,50,51,52,53,54,56,59,60,17,55],
    'RIESGO ADICTIVO': [9,5,17,19,21,22,32],
    'VIOLENCIA': [17,19,21,53,56,20,51,68,74,62],
    'LIDERAZGO NEGATIVO': [68,63,65,66,32,59,55,24],
}
